Loading dataset...
Resolving data files: 100%|██████████| 114/114 [00:00<00:00, 173.34it/s]
Downloading data files: 100%|██████████| 1/1 [00:00<00:00, 22.07it/s]
Extracting data files: 100%|██████████| 1/1 [00:00<00:00,  4.57it/s]
Generating train split: 100%|██████████| 6315233/6315233 [00:57<00:00, 110147.96 examples/s]
Traceback (most recent call last):
  File "/n/netscratch/dam_lab/Lab/hdiaz/ft_project/finetune.py", line 31, in <module>
    dataset_dict = load_dataset(
                   ^^^^^^^^^^^^^
  File "/n/netscratch/dam_lab/Lab/hdiaz/.conda/envs/env3/lib/python3.12/site-packages/datasets/load.py", line 2149, in load_dataset
    ds = builder_instance.as_dataset(split=split, verification_mode=verification_mode, in_memory=keep_in_memory)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/netscratch/dam_lab/Lab/hdiaz/.conda/envs/env3/lib/python3.12/site-packages/datasets/builder.py", line 1173, in as_dataset
    raise NotImplementedError(f"Loading a dataset cached in a {type(self._fs).__name__} is not supported.")
NotImplementedError: Loading a dataset cached in a LocalFileSystem is not supported.
